# Generated by Django 5.0.2 on 2024-02-28 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('fullname', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=16)),
                ('type', models.CharField(choices=[('chr', 'Character'), ('prp', 'Prop'), ('env', 'Environment')], max_length=16)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assets', to='pipeline_db.project')),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=16)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sequences', to='pipeline_db.project')),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=16)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shots', to='pipeline_db.project')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shots', to='pipeline_db.sequence')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=16)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='pipeline_db.asset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='pipeline_db.project')),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='pipeline_db.shot')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('element', models.CharField(max_length=16)),
                ('number', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=16)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='versions', to='pipeline_db.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='versions', to='pipeline_db.task')),
            ],
        ),
    ]
