# Generated by Django 5.0.2 on 2024-02-28 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
