# Generated by Django 5.0.2 on 2024-02-28 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_db', '0003_alter_shot_project_alter_shot_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shots', to='pipeline_db.project'),
        ),
        migrations.AlterField(
            model_name='shot',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shots', to='pipeline_db.sequence'),
        ),
        migrations.AlterField(
            model_name='task',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='pipeline_db.asset'),
        ),
        migrations.AlterField(
            model_name='task',
            name='shot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='pipeline_db.shot'),
        ),
    ]
